### ISSUE TITLE
datasource for Cao et al. cerebrum processing

### ISSUE THREAD

**Issue by JonnyBaseball** [erwinerdem/STEAP#1]
Hello,

I hope you are well! 

I am somewhat new to scNRA processing, but was working through your jupytr notebook examples for processing the raw scNRA to ES data for CELLECT.  I'm particularly interested in the fetal brain tissue and was trying the cerebrum file.  What file did you use for the input?  I've checked the GEO database and there are several listed samples for "brain" tissue: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE156793.  

Very respectfully,
Dab

**Comment by erwinerdem** [comment]
Hi,

I acquired the Descartes datasets from the site: 
https://descartes.brotmanbaty.org/bbi/human-gene-expression-during-development/
Hope this helps!

**Comment by JonnyBaseball** [comment]
This is fantastic!  Thank you!!

V/R
Dan
